name: mosand_customer
description: "Musaned Customer - منصة مُساند للأسر المنتجة - تطبيق العملاء"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4

  # State Management
  provider: ^6.1.2

  # UI
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

  # Utils
  intl: ^0.19.0
  uuid: ^4.5.1
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/loge.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
